#模板配置
spring:
  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

#数据库配置
spring：
  datasource：
    driver-class-name： com.mysql.jdbc.Driver
    url： jdbc:mysql://www.gnok.xin:3306/la_damo
    username：root
    password：123456

spring：
  jpa：
    hibernate
    show-sql： true
      ddl-auto：update

spring
  jackson
    serialization
      indent_output：true
